CREATE TABLE `configuracoes_financeiras` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pixAtivo` boolean DEFAULT false,
	`pixTipoChave` enum('cpf','cnpj','email','telefone','aleatoria'),
	`pixChave` varchar(255),
	`pixNomeBeneficiario` varchar(255),
	`pixCidade` varchar(100),
	`pixQrCodeUrl` text,
	`boletoAtivo` boolean DEFAULT false,
	`boletoInstrucoes` text,
	`boletoLinkPadrao` text,
	`cartaoAtivo` boolean DEFAULT false,
	`cartaoLinkPagamento` text,
	`cartaoDescricao` text,
	`notaFiscalAtivo` boolean DEFAULT false,
	`notaFiscalInstrucoes` text,
	`notaFiscalEmail` varchar(320),
	`valorMensalidade` decimal(10,2),
	`diaVencimento` int DEFAULT 10,
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `configuracoes_financeiras_id` PRIMARY KEY(`id`)
);
